version: '3'
services:
  web:
    build:
      context: .
      args:
        S3_BUCKET_NAME: ${S3_BUCKET_NAME}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_REGION: ${AWS_REGION}
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - S3_BUCKET_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    volumes:
      - .:/rails
    ports:
      - "3001:3000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: video_uploader_development
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
